
INSERT INTO `user` (`id`, `password`, `user_name`, `email`) VALUES ('1', '123456', 'amit', 'amtydv630@gmail.com');
INSERT INTO `user` (`id`, `password`, `user_name`, `email`) VALUES ('2', '123456', 'pawan', 'pawancontactinfo@gmail.com');
INSERT INTO `user` (`id`, `password`, `user_name`, `email`) VALUES ('3', '123456', 'ravi', 'ravisinghkushwaha@gmail.com');


INSERT INTO `event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('1', 'CHAOS 2020', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
INSERT INTO `event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('2', 'PowerApps Traininig', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
INSERT INTO `event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('3', 'college fest', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
INSERT INTO `event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('4', 'college fest', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
INSERT INTO `event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('5', 'college fest', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');



INSERT INTO `special_event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('1', 'CHAOS 2020', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
INSERT INTO `special_event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('2', 'PowerApps Traininig', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
INSERT INTO `special_event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('3', 'college fest', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
INSERT INTO `special_event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('4', 'college fest', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
INSERT INTO `special_event` (`id`, `event_name`, `place`, `event_description`, `link`) VALUES ('5', 'college fest', 'Allahabad', 'Others, Literature, Concert, Cultural, Seminars, Fun & Other Events, Hobbies & Interest, Technical, Online Events, General, Gaming, Sports, Merchandise','https://www.thecollegefever.com/college-events/city/indian%20statistical%20institute/chaos-2020-usONYZhRxL');
